parameters:
  - name: metadataURL
    displayName: 'URL for metadata for which SDK generation will happen:'
    type: string
    default: 'https://graph.microsoft.com/stagingv1.0/`$metadata'

  - name: metadataVersion
    displayName: 'Metadata version, supported values: v1.0, beta'
    type: string
    default: 'v1.0'

variables:
  buildConfiguration: 'Release'
  typewriterSolution: 'MSGraph-SDK-Code-Generator/**/Typewriter.sln'
  apidoctorSolution: 'apidoctor/**/*.sln'
  snippetLanguages: 'C#' # possible values: 'C#,JavaScript,Objective-C,Java'
  runSettingsFile: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/CSharpArbitraryDllTests/Test.runsettings'
  metadataURL: ${{ parameters.metadataURL }}
  metadataVersion: ${{ parameters.metadataVersion }}