steps:
- task: PowerShell@2
  displayName: 'Set dll path for the .NET framework DLL for type summary generation'
  inputs:
    targetType: inline
    workingDirectory: '$(Build.SourcesDirectory)'
    script: |
      $allGeneratedDlls = Get-ChildItem $dir -Include Microsoft.Graph.dll -Recurse
      $dotNetFrameworkDll = $allGeneratedDlls | Where-Object { !$_.FullName.Contains("obj") -and !$_.FullName.Contains("netstandard") }
      $dotNetFrameworkDllPath = $dotNetFrameworkDll.FullName
      Write-Host "Path to Microsoft.Graph.dll (.NET Framework): $dotNetFrameworkDllPath"
      Write-Host "##vso[task.setvariable variable=dotNetFrameworkDllPath]$dotNetFrameworkDllPath"

- task: PowerShell@2
  displayName: 'Generate type summary'
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/msgraph-sdk-dotnet/scripts/generateTypeSummary.ps1'
    arguments: '-dllPath $(dotNetFrameworkDllPath) -outputPath $(Build.ArtifactStagingDirectory)\typeSummary.txt'
  enabled: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish type summary as artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\typeSummary.txt'
    ArtifactName: 'TypeSummary'
    publishLocation: 'Container'
