# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none
pr: none
schedules:
- cron: "0 12 * * *"
  displayName: 'Run Raptor everyday at noon'
  branches:
    include:
    - zengin/arbitraryDll
  always: true

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: master
   - repository: apidoctor
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/apidoctor
     ref: generate-snippets
   - repository: microsoft-graph-explorer-api
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-explorer-api
     ref: dev
   - repository: MSGraph-SDK-Code-Generator
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/MSGraph-SDK-Code-Generator
     ref: master
   - repository: msgraph-sdk-dotnet
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/msgraph-sdk-dotnet
     ref: dev
   - repository: msgraph-metadata
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/msgraph-metadata

parameters:
- name: shouldRunKnownFailures
  displayName: 'Should we run known failure tests?'
  type: boolean
  default: false

pool:
  vmImage: 'windows-latest'

variables:
  - template: variables.yml

steps:
- template: checkouts.yml
- template: snippet-generation.yml
- template: sdk-generation.yml
- template: regular-tests.yml
- template: known-failure-tests.yml
- template: generate-type-summary.yml
